# Dockerfile para desplegar la calculadora con Nginx
FROM nginx:alpine
# Copia los archivos de la calculadora al directorio por defecto de Nginx
COPY ../../../../calculator /usr/share/nginx/html
EXPOSE 80
